### ISSUE TITLE
Теми курсових 2021

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/ProgIngContrSystems#53]
Тут обговорюються теми курсових на 2021 рік.

**Comment by pupenasan** [comment]
Приклади тем [тут](https://github.com/pupenasan/ProgIngContrSystems/blob/master/%D0%9A%D1%83%D1%80%D1%81%D0%BE%D0%B2%D0%B8%D0%B9/%D0%B2%D1%80%D1%96%D0%B0%D0%BD%D1%82%D0%B8.md)

**Comment by Haiduk-Oleksandr** [comment]
автоматичне контролювання температури об'єктів

**Comment by pupenasan** [comment]
> 
> 
> Тема : Автоматичне контролювання температури об'єктів

Дуже загальна тема. Не зрозуміло яких об'єктів і що значить `автоматичне контролювання`.

**Comment by Haiduk-Oleksandr** [comment]
Автоматичне сканування температури людини з подальшим допуском, або забороною на вхід.

**Comment by pupenasan** [comment]
> Автоматичне сканування температури людини з подальшим допуском, або забороною на вхід.

- Самі будете чи з командою?
- Чому тоді не "автоматичне фотографування об'єктів на відстані з вказаним діапазоном температури"?

**Comment by Haiduk-Oleksandr** [comment]
> > Автоматичне сканування температури людини з подальшим допуском, або забороною на вхід.
> 
> * Самі будете чи з командою?
> * Чому тоді не "автоматичне фотографування об'єктів на відстані з вказаним діапазоном температури"?

- Там де я записаний ніхто не планує щось робити. Так що мабуть сам.
- На мою думку зараз дуже актуально автоматизувати вимір температури людей на входах в приміщення та приватні зони.

**Comment by pupenasan** [comment]
Тоді краще "Дистанційний контроль температури людей в приміщенні"

**Comment by pupenasan** [comment]
Додаткові стандартні теми (2023):
- голосовий помічник через використання ChatGpt або аналогічні сервіси
Додаткові нестандартні теми (2023):
- Інтегрування з Facebook + MongoDB + https://docs.appsmith.com (на 3-х)
- підготовка і запис лекції по MongoDB з прикладами на Node-RED (на 1 людину)
- підготовка і запис лекції по appsmith https://docs.appsmith.com (на 1 людину)
- API до LnkedIn/Facebook (на 1 людину)

**Comment by pupenasan** [comment]
- Автоматизоване перетворення вебінару на YouTube в текстову форму з перекладом

**Comment by pupenasan** [comment]
- аналіз документу Word, витягування формул і перетворення в Latex.

**Comment by pupenasan** [comment]
Повідомлення від Сергія Третяка

ну от маю приклад простенької автоматизації з використанням мікроконтролерів.
є лабораторний блок живлення саморобний, струми протікають там часто відчутні, під 20ампер. Потрібно охолодження. Але так як все живиться від акумуляторів то не бажано весь час тримати включеними вентилятори. Та й шум лишній. Вирішили робити на Arduino.
Що зроблено:
взято мікроконтролер(в тому випадку ESP32 C3 Mini), підєднано до нього  INA-226 для зняття показників протікаючого струму, та напруги. Шунт замінено звісно на відповідаючий протікаючим струмам.
Відповідно до отриманих значень формується ШИМ заданої скважності/заповнення. Пін з ШИМ підєднано до транзисторного модуля котрий живить 12В вентилятори в корпусі.
Якщо потужність перевищує задану то вмикається пін до котрого підключено активний buzzer/beeper. 
ось така проста автоматизація на стику домашнього і виробничого використання.

А так то більшість автоматизацій у мене робиться силами Home Assistant, як найбільш простий варіант. Для вашого випадку напевне не актуально, хіба що сама ідея. Але мушу попередити що я ретроград і китайським приладам не довіряю. Тому 90% автоматизацій виконують лише інформаційну чи дорадчу дію.

-стандартне увімкнення світла по датчику руху.
-увімкнення світла по zigbee датчику вібрацій приліпленому до сходів.
 варіант 2. Вмикаємо не освітлення, а інформаційний кольоровий діод біля компютера. Так ніхто не може піднятися на поверх "не поміченим" 😄.
-керування освітленням і іншими діями з пульта від телевізора. Реалізовано на базі ІЧ-сенсора засунутого в ЕСП32. В сам код ESPhome(гадаю в інших середовищах логіка така сама буде) засунуто шаблони сигналів від відповідних кнопок пульта. І на основі спрацювання виконуються певні дії. Правда на зарашній час дія привязана лише до однієї кнопки, котра перемикає перемикач віртуальний, на основі чого й виконуються дії основною системою. Зроблено так бо сам сигнал з пульта дуже короткочасний і віддалена система може сприйняти його короткотривалість як випадкові завади. Тому локальний сигнальний перемикач перемикається на 1 секунду, щоб точно було ініційоване спрацювання.
```
binary_sensor:
  - platform: remote_receiver
    name: "but1"
    pronto:
      data: "0000 006D 0022 0000 015C 00AC 0016 0015 0016 0015 0017 003F 0017 0016 0015 0015 0016 0015 0017 0014 0017 0014 0017 0041 0015 0041 0015 0017 0015 0041 0015 0041 0015 0041 0015 0041 0015 0042 0015 0040 0017 0014 0017 0015 0015 0015 0017 0041 0015 0017 0015 0017 0015 0015 0017 0015 0015 0042 0015 0040 0017 0041 0015 0017 0015 0040 0016 0040 0016 0042 0015 0181 06C3"
    on_state:
      then:
        - switch.turn_on: but4
        - delay: 1s
        - switch.turn_off: but4
  - platform: remote_receiver
    name: "but2"
    pronto:
      data: "0000 006D 0022 0000 015C 00AD 0015 0016 0015 0015 0017 0041 0015 0015 0016 0017 0015 0015 0017 0016 0015 0017 0015 0040 0017 0041 0015 0015 0017 0041 0015 0040 0017 0041 0015 0040 0016 0040 0017 0014 0017 003F 0017 0015 0015 0017 0015 0040 0017 0015 0015 0016 0015 0017 0015 0040 0017 0016 0015 0042 0015 0042 0015 0015 0017 003F 0017 003F 0016 0042 0015 06C3"
```
-порівняння температур від вуличного і кімнатного датчика температур. І якщо "на вулиці" тепліше то озвучує пропозицію відкрити вікна в кімнаті.
-заміри вологості та якості повітря в кімнаті. Якщо значення завеликі то озвучує пропозицію відкрити вікна.
-виклик HTTP-запиту котрий в GET запиті передає значення електричного лічильника у БД на сайті(веду графік споживання електроенергії досить давно, ще до знайомства з розумним будинком, тому раніше та база наповнювалась вручну). В якості пристрою обліку електроенергії використано PZEM-004, як такий що має 0,5-1% похибку відносно повіреного електричного лічильника.
-відсилання в Telegram ранкових зведень статистики(скільки електроенергії використано за попередню добу, температура на вулиці в цей момент) .Правда як і попеердня ця вже вимагає наявності доступу до інтернету на пристрої.
P.S. Описую лише самі ідеї, гадаю конкретика вам не актуальна через інший стек використовуємих технологій. Ну і звісно це все окремі автоматизації, на повні курсові не тягнуть 🙂
хіба що з світлом можна заморочитися(я трішки заморочився) і по сигналам від PIR датчиків керувати освітленням. Наприклад по коридорному сенсору вмикаємо в коридорі освітлення. Якщо спрацьовує кімнатний сенсор і включене освітлення в коридорі то вимикаємо коридорне освітлення, бо обєкт вже у кімнаті.
